@extends('layouts.app')

@section('title', $page->meta_title)

@section('meta')
    <meta name="description" content="{{ $page->meta_description }}">
    @if($page->meta_keywords)
        <meta name="keywords" content="{{ $page->meta_keywords }}">
    @endif
@endsection

@section('content')
<!-- Header Section -->
<div class="policy-header bg-light py-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto text-center">
                <h1 class="display-5 fw-bold text-primary mb-3">{{ $page->title }}</h1>
                @if($page->excerpt)
                    <p class="lead text-muted">{{ $page->excerpt }}</p>
                @endif
                <div class="text-muted small">
                    <i class="bi bi-calendar-event me-1"></i>
                    Cập nhật lần cuối: {{ $page->updated_at->format('d/m/Y') }}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Breadcrumb -->
<div class="container py-3">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('home') }}">Trang chủ</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ $page->title }}</li>
        </ol>
    </nav>
</div>

<div class="container py-5">
    <div class="row">
        <!-- Table of Contents (Sidebar) -->
        <div class="col-lg-3">
            <div class="toc-sidebar position-sticky" style="top: 20px;">
                <div class="card">
                    <div class="card-header">
                        <h5 class="mb-0">Mục lục</h5>
                    </div>
                    <div class="card-body">
                        <nav id="table-of-contents">
                            <!-- TOC will be generated by JavaScript -->
                        </nav>
                    </div>
                </div>

                <!-- Quick Links -->
                <div class="card mt-4">
                    <div class="card-header">
                        <h5 class="mb-0">Liên kết hữu ích</h5>
                    </div>
                    <div class="card-body">
                        <div class="d-grid gap-2">
                            <a href="{{ route('pages.show', 'chinh-sach-bao-mat') }}" class="btn btn-outline-primary btn-sm">
                                <i class="bi bi-shield-check me-1"></i> Chính sách bảo mật
                            </a>
                            <a href="{{ route('pages.show', 'dieu-khoan-su-dung') }}" class="btn btn-outline-primary btn-sm">
                                <i class="bi bi-file-text me-1"></i> Điều khoản sử dụng
                            </a>
                            <a href="{{ route('pages.show', 'chinh-sach-doi-tra') }}" class="btn btn-outline-primary btn-sm">
                                <i class="bi bi-arrow-repeat me-1"></i> Chính sách đổi trả
                            </a>
                            <a href="{{ route('pages.show', 'chinh-sach-giao-hang') }}" class="btn btn-outline-primary btn-sm">
                                <i class="bi bi-truck me-1"></i> Chính sách giao hàng
                            </a>
                            <a href="{{ route('pages.show', 'lien-he') }}" class="btn btn-outline-secondary btn-sm">
                                <i class="bi bi-telephone me-1"></i> Liên hệ hỗ trợ
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Main Content -->
        <div class="col-lg-9">
            <div class="policy-content">
                <!-- Important Notice -->
                <div class="alert alert-info mb-4">
                    <div class="d-flex">
                        <i class="bi bi-info-circle me-2 mt-1"></i>
                        <div>
                            <strong>Lưu ý quan trọng:</strong> 
                            Chính sách này có hiệu lực từ ngày {{ $page->updated_at->format('d/m/Y') }}. 
                            Vui lòng đọc kỹ và thường xuyên kiểm tra để cập nhật những thay đổi mới nhất.
                        </div>
                    </div>
                </div>

                <!-- Page Content -->
                <div class="content-wrapper" id="main-content">
                    {!! $page->content !!}
                </div>

                <!-- Contact Section -->
                <div class="contact-section mt-5 p-4 bg-light rounded">
                    <h3 class="mb-3">Cần hỗ trợ thêm?</h3>
                    <p class="mb-3">
                        Nếu bạn có bất kỳ câu hỏi nào về chính sách này hoặc cần làm rõ thêm thông tin, 
                        vui lòng liên hệ với chúng tôi qua các kênh sau:
                    </p>
                    
                    <div class="row">
                        <div class="col-md-4 mb-3">
                            <div class="contact-item text-center">
                                <i class="bi bi-telephone text-primary mb-2" style="font-size: 2rem;"></i>
                                <h6>Hotline</h6>
                                <a href="tel:0123456789" class="text-decoration-none">0123 456 789</a>
                            </div>
                        </div>
                        <div class="col-md-4 mb-3">
                            <div class="contact-item text-center">
                                <i class="bi bi-envelope text-primary mb-2" style="font-size: 2rem;"></i>
                                <h6>Email</h6>
                                <a href="mailto:support@fruitshop.com" class="text-decoration-none">support@fruitshop.com</a>
                            </div>
                        </div>
                        <div class="col-md-4 mb-3">
                            <div class="contact-item text-center">
                                <i class="bi bi-chat-dots text-primary mb-2" style="font-size: 2rem;"></i>
                                <h6>Live Chat</h6>
                                <a href="{{ route('pages.show', 'lien-he') }}" class="text-decoration-none">Bắt đầu chat</a>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Last Updated Info -->
                <div class="last-updated mt-4 p-3 border-start border-primary border-3 bg-light">
                    <small class="text-muted">
                        <i class="bi bi-clock me-1"></i>
                        <strong>Lần cập nhật cuối:</strong> {{ $page->updated_at->format('d/m/Y \l\ú\c H:i') }}
                        @if($page->updater)
                            bởi {{ $page->updater->name }}
                        @endif
                    </small>
                </div>

                <!-- Navigation -->
                <div class="content-navigation mt-4">
                    <div class="row">
                        <div class="col-6">
                            <a href="{{ route('home') }}" class="btn btn-outline-secondary">
                                <i class="bi bi-house me-1"></i> Về trang chủ
                            </a>
                        </div>
                        <div class="col-6 text-end">
                            <button onclick="scrollToTop()" class="btn btn-outline-primary">
                                <i class="bi bi-arrow-up me-1"></i> Lên đầu trang
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('styles')
<style>
.policy-header {
    border-bottom: 2px solid #e9ecef;
}

.toc-sidebar {
    z-index: 1020;
}

.content-wrapper {
    font-size: 1rem;
    line-height: 1.7;
    color: #333;
}

.content-wrapper h1,
.content-wrapper h2,
.content-wrapper h3,
.content-wrapper h4,
.content-wrapper h5,
.content-wrapper h6 {
    color: #2c3e50;
    margin-top: 2.5rem;
    margin-bottom: 1rem;
    padding-bottom: 0.5rem;
    border-bottom: 1px solid #e9ecef;
}

.content-wrapper h1 {
    font-size: 2rem;
    color: #3498db;
    border-bottom: 2px solid #3498db;
}

.content-wrapper h2 {
    font-size: 1.5rem;
    color: #2980b9;
}

.content-wrapper h3 {
    font-size: 1.3rem;
}

.content-wrapper p {
    margin-bottom: 1.2rem;
    text-align: justify;
}

.content-wrapper ul,
.content-wrapper ol {
    margin-bottom: 1.5rem;
    padding-left: 2rem;
}

.content-wrapper li {
    margin-bottom: 0.5rem;
}

.content-wrapper blockquote {
    border-left: 4px solid #3498db;
    background-color: #f8f9fa;
    padding: 1rem 1.5rem;
    margin: 1.5rem 0;
    font-style: italic;
    border-radius: 0 8px 8px 0;
}

.content-wrapper table {
    width: 100%;
    border-collapse: collapse;
    margin: 1.5rem 0;
    border: 1px solid #dee2e6;
}

.content-wrapper table th,
.content-wrapper table td {
    border: 1px solid #dee2e6;
    padding: 0.75rem;
    text-align: left;
}

.content-wrapper table th {
    background-color: #f8f9fa;
    font-weight: 600;
    color: #2c3e50;
}

.content-wrapper table tr:nth-child(even) {
    background-color: #f8f9fa;
}

.content-wrapper strong {
    color: #2c3e50;
    font-weight: 600;
}

.content-wrapper a {
    color: #3498db;
    text-decoration: none;
}

.content-wrapper a:hover {
    color: #2980b9;
    text-decoration: underline;
}

/* Table of Contents */
#table-of-contents {
    max-height: 400px;
    overflow-y: auto;
}

#table-of-contents ul {
    list-style: none;
    padding-left: 0;
    margin: 0;
}

#table-of-contents ul ul {
    padding-left: 1rem;
    margin-top: 0.25rem;
}

#table-of-contents a {
    display: block;
    padding: 0.25rem 0.5rem;
    color: #6c757d;
    text-decoration: none;
    border-radius: 4px;
    font-size: 0.9rem;
    transition: all 0.3s ease;
}

#table-of-contents a:hover,
#table-of-contents a.active {
    color: #3498db;
    background-color: #e3f2fd;
}

/* Contact items */
.contact-item {
    transition: transform 0.3s ease;
}

.contact-item:hover {
    transform: translateY(-2px);
}

.contact-item a {
    color: inherit;
}

.contact-item a:hover {
    color: #3498db;
}

/* Scroll behavior */
html {
    scroll-behavior: smooth;
}

/* Responsive */
@media (max-width: 991.98px) {
    .toc-sidebar {
        position: static !important;
        margin-bottom: 2rem;
    }
}

@media (max-width: 768px) {
    .content-wrapper {
        font-size: 0.95rem;
    }
    
    .content-wrapper h1 {
        font-size: 1.5rem;
    }
    
    .content-wrapper h2 {
        font-size: 1.3rem;
    }
    
    .content-wrapper h3 {
        font-size: 1.1rem;
    }
}
</style>
@endpush

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function() {
    generateTableOfContents();
    setupScrollSpy();
});

function generateTableOfContents() {
    const content = document.getElementById('main-content');
    const toc = document.getElementById('table-of-contents');
    const headings = content.querySelectorAll('h1, h2, h3, h4, h5, h6');
    
    if (headings.length === 0) {
        toc.innerHTML = '<p class="text-muted small">Không có mục lục</p>';
        return;
    }
    
    let tocHTML = '<ul>';
    let currentLevel = 0;
    
    headings.forEach((heading, index) => {
        const level = parseInt(heading.tagName.substr(1));
        const id = `section-${index}`;
        heading.id = id;
        
        const title = heading.textContent.trim();
        
        if (level > currentLevel) {
            for (let i = currentLevel; i < level - 1; i++) {
                tocHTML += '<li><ul>';
            }
            if (currentLevel > 0) tocHTML += '<li><ul>';
        } else if (level < currentLevel) {
            for (let i = level; i < currentLevel; i++) {
                tocHTML += '</ul></li>';
            }
        } else if (currentLevel > 0) {
            tocHTML += '</li>';
        }
        
        tocHTML += `<li><a href="#${id}" class="toc-link">${title}</a>`;
        currentLevel = level;
    });
    
    for (let i = 0; i < currentLevel; i++) {
        tocHTML += '</li></ul>';
    }
    
    toc.innerHTML = tocHTML;
}

function setupScrollSpy() {
    const tocLinks = document.querySelectorAll('.toc-link');
    const headings = document.querySelectorAll('#main-content h1, #main-content h2, #main-content h3, #main-content h4, #main-content h5, #main-content h6');
    
    function updateActiveLink() {
        let activeIndex = -1;
        
        for (let i = 0; i < headings.length; i++) {
            const rect = headings[i].getBoundingClientRect();
            if (rect.top <= 100) {
                activeIndex = i;
            }
        }
        
        tocLinks.forEach((link, index) => {
            link.classList.toggle('active', index === activeIndex);
        });
    }
    
    window.addEventListener('scroll', updateActiveLink);
    updateActiveLink(); // Initial call
}

function scrollToTop() {
    window.scrollTo({
        top: 0,
        behavior: 'smooth'
    });
}

// Smooth scroll for TOC links
document.addEventListener('click', function(e) {
    if (e.target.classList.contains('toc-link')) {
        e.preventDefault();
        const targetId = e.target.getAttribute('href').substr(1);
        const targetElement = document.getElementById(targetId);
        
        if (targetElement) {
            targetElement.scrollIntoView({
                behavior: 'smooth',
                block: 'start'
            });
        }
    }
});
</script>
@endpush